[tool.poetry]
name = "rag-stack"
version = "0.1.0"
description = ""
authors = ["ayan <ayan@psychic.dev>"]
packages = [{include = "server"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
fastapi = "^0.92.0"
uvicorn = "^0.20.0"
python-dotenv = "^0.21.1"
pydantic = "^1.10.5"
langchain = "^0.0.233"
strenum = "^0.4.15"
qdrant-client = "^1.3.1"
sentence-transformers = "^2.2.2"
python-multipart = "^0.0.6"
gpt4all = "^1.0.5"
pymupdf = "^1.22.5"
supabase = "^1.0.3"
poetry-dotenv-plugin = "^0.2.0"
openai = "^0.27.8"
torch = { url = "http://download.pytorch.org/whl/cpu/torch-2.0.1%2Bcpu-cp310-cp310-linux_x86_64.whl" }

[tool.poetry.scripts]
start = "server.main:start"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
